# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: 'static'

# The type key specifies the language and version for your application.
type: 'nodejs:16'

build:
    flavor: none

# The hooks that will be triggered when the package is deployed.
hooks:
  build: bash ./static.platform.sh build
  deploy: bash ./static.platform.sh deploy
  post_deploy: bash ./static.platform.sh post_deploy

# The size of the persistent disk of the application (in MB).
disk: 1024

mounts:
    'volume':
        source: local
        source_path: volume


# The configuration of the application when it is exposed to the web.
web:
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'public'
            index: ['index.html']
            scripts: false
            allow: true
            passthru: false
            expires: 6h

variables:
    env:
        APP_VOLUME: '/app/volume'
        CHOKIDAR_USEPOLLING: true
        DISABLE_TSCONFIG_PATHS_PLUGIN: '1'
