
"https://edit.{default}/":
    type: upstream
    upstream: "edit:http"
    cache:
        enabled: false
"https://{default}/":
    type: upstream
    upstream: "static:http"
    id: 'docs-env-route-id'
    ssi:
        enabled: true
